[package]
name = "squid_wtf_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
error-chain = "0.12.4"
reqwest = "0.12.15"
substring = "1.4.5"
serde_json = "1.0.140"
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"]}
